---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: https://webhook.site/83ee4946-5c3b-43a0-9ba4-f1b3a0126372
sections:
- type: directory
  path: ''
  label: Not French
  create: all
  match: "**/*"
  exclude: "{ fr/*, _posts/* }"
  templates:
  - page
- type: directory
  path: ''
  label: Root pages
  create: documents
  match: "*.md"
  exclude: "{404\\.md,index\\.md}"
  templates:
  - default
- type: heading
  label: Content
- type: jekyll-posts
  label: Posts
  create: documents
  templates:
  - post
  - example
- type: jekyll-pages
  label: Pages
  create: all
  templates:
  - landing-page
  - default
- type: directory
  path: _people
  label: People
  create: all
  match: "*"
  templates:
  - person
- type: directory
  path: _projects
  label: Projects
  create: documents
  match: "*.md"
  templates:
  - project
- type: document
  path: _data/information.yml
  label: Contact Information
- type: document
  path: _config.yml
  label: Config
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  - RUBY_VERSION=2.6.1
  publish_env:
  - JEKYLL_ENV=production
  - BUILD_DIR=docs
  preview_output_directory: _site
  output_directory: docs/_site
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d site
