---
new_page_extension: md
auto_deploy: true
admin_path: "/admin/"
webhook_url: https://webhook.site/83ee4946-5c3b-43a0-9ba4-f1b3a0126372
sections:
- type: heading
  label: Content
- type: jekyll-posts
  label: Posts
  create: all
  templates:
  - post
- type: jekyll-pages
  label: Pages
  create: all
  templates:
  - image-gallery
  - landing-page
  - default
- type: directory
  path: _people
  label: People
  create: documents
  match: "*"
  templates:
  - person
- type: directory
  path: _projects
  label: Projects
  create: documents
  match: "*.md"
  templates:
  - project
- type: heading
  label: Data
- type: document
  path: _data/category.json
  label: Category
- type: document
  path: _data/categories.yml
  label: Categories
- type: document
  path: _data/menus.yml
  label: Menus
- type: document
  path: _data/information.yml
  label: Contact Information
upload_dir: uploads
public_path: https://forestry-demo.netlify.com/uploads
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d site
