---
label: default
hide_body: true
display_field: url
fields:
- type: text
  name: title
  label: Title
  config:
    required: true
- name: url
  type: text
  config:
    required: false
  label: url
- type: textarea
  name: description
  label: Description
  description: A short description of the page
  config:
    required: true
- type: datetime
  name: publish_date
  label: Publish Date
  config:
    required: true
- type: text
  name: layout
  label: layout
  hidden: true
  default: post
  config:
    required: true
- name: weight
  type: number
  label: weight
  description: ''
  default: 0
  required: true
  config:
    min: 0
    max: 100
    step: 1
pages:
- en/this-is-a-page.md
- en/where-do-i-go.md
- forestry.md
- fr/this-is-a-page.md
- fr/this-should-be-in-fr-folder.md
- hello.md
