---
label: Sortable list empty values
hide_body: false
fields:
- name: reading_list
  type: list
  config:
    use_select: true
    min: '0'
    max: '3'
    source:
      type: pages
      section: jekyll-posts
  label: reading list
pages:
- _posts/sortable.md
